# Default values for demo-app chart
# Usage: helm upgrade --install demo-app ./charts/demo-app

containers:
  app:
    image:
      repository: ghcr.io/m4s-b3n/cnpg-blue-green/demo-app
      tag: 1.0.0
    env:
      PGHOST:
        value: "pgbouncer.cnpg-demo.svc.cluster.local"
      PGPORT:
        value: "5432"
      PGDATABASE:
        value: "appdb"
      PGUSER:
        value: "appuser"
      PGPASSWORD:
        valueFrom:
          secretKeyRef:
            name: myapp-app-user
            key: password
            external: true
      PGSSLMODE:
        value: "disable"
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "64Mi"
        cpu: "50m"
    securityContext:
      runAsUser: 65534 # nobody on Alpine
      runAsGroup: 65534
