{{- if .Values.initdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cluster.name }}-initdb
  labels:
    {{- include "pg-cluster.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.initdb.scripts }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
{{- end }}
