{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-app-user
  labels:
    {{- include "pg-cluster.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}
{{- end }}
